### ISSUE TITLE
JSON File Size Too Large for an Int32

### ISSUE THREAD

**Issue by doug-shontz** [kfrancis/wistia.net#2]
Thanks so much for this great library.  We have some very large files that we serve up in our Wistia account, and, on a few of them, I am receiving this error.

{"JSON integer 2319964422 is too large or small for an Int32. Path 'assets[0].fileSize', line 1, position 652."}

With the JSON integer being whatever the actual Wistia return value is.  This happens when calling the WistiaDataClient.Media.GetById.

Thanks so much!

**Comment by kfrancis** [comment]
I'll put a new release up, looks like it's as simple as using a long instead of int there

**Comment by kfrancis** [comment]
Released in v1.0.6110.19776

**Comment by doug-shontz** [comment]
Thank you, sir!
